### ISSUE TITLE
Decide on colour scheme

### ISSUE THREAD

**Issue by ChrisCooper0** [MK-Codecademy/itinerary-app#11]
Are we happy to use the built-in Tailwind colour scheme and if so, shall we agree on primary/secondary text and background colours from the default palette below?

https://tailwindcss.com/docs/customizing-colors#default-color-palette 

Once decided, let's update the contributing.md file, any components not using our new colour scheme and we can close this issue!

**Comment by willgarrett64** [comment]
@ChrisCooper0 / @Hyosssssun - I am happy to use the tailwind default colour scheme, at least for now. We can always change it later if we want to. 

I'm a sucker for purple for some unknown reason (my chrome/windows/linux themes are all purple!). So I'd be happy to have Purple/Fuschia 800 or 900 as a primary colour, with white text. 

Background for the main site could be an off-white colour to make it easier on the eyes, with potentially a dark-grey or black font colour. 

![image](https://user-images.githubusercontent.com/74154911/166140118-97aba4a3-d838-45bb-9e63-41297d036c84.png)

This is of course just my biased opinion, so feel free to fire away with other ideas.

**Comment by ChrisCooper0** [comment]
Yeah I'm happy with purple

**Comment by ChrisCooper0** [comment]
@Hyosssssun any objections to the Purple theme? If not I'll close this issue :)

**Comment by Hyosssssun** [comment]
@ChrisCooper0 Yes I am happy with this theme! Nice!
