### ISSUE TITLE
Landing Page - log in card

### ISSUE THREAD

**Issue by willgarrett64** [MK-Codecademy/itinerary-app#8]
This issues involves creating the log in card (component) and importing it into the landing page - https://github.com/MK-Codecademy/itinerary-app/issues/5.  

The designs for it at the moment are very basic, but feel free to get creative. Overall designs will be revisited later. 
![image](https://user-images.githubusercontent.com/74154911/165721491-92c8a8fb-1f71-4557-8168-96ad33e26563.png)

Here's how it will slot into the landing page:
![image](https://user-images.githubusercontent.com/74154911/165721645-8b1d7ea7-b664-47c5-b21b-4ab54ec18414.png)

**Comment by ChrisCooper0** [comment]
@willgarrett64 - Not sure how far along you are with the other card issue (Plan new trip) but I'm going to change this to be a re-usable card which has props for the title and button text. Then you can use it for your component and extend with the additional bits
